version: '3.8'

services:
  # 1. Makine: Bizim yazdığımız C# Uygulaması
  benim-api:
    build: . 
    
    depends_on:
      - veritabani

  # 2. Makine: PostgreSQL Veri Tabanı
  veritabani:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_SIFRE}
      POSTGRES_DB: oyun_verileri
    
    volumes:
      - db_data:/var/lib/postgresql/data
      
   nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - benim-api
      
volumes:
  db_data:
