version: '3.8'

services:
  # 1. Makine: Bizim yazdığımız C# Uygulaması
  benim-api:
    build: . 
    ports:
      - "80:8080"
    depends_on:
      - veritabani

  # 2. Makine: PostgreSQL Veri Tabanı
  veritabani:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: gizlisifre123
      POSTGRES_DB: oyun_verileri
    ports:
      - "5432:5432"
